name: Project CICD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository to Ubuntu Runner
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing Dependecies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --check "**/*.{html,css,js}"

      - name: Run HTML Hint
        run: npx htmlhint "**/*.html"

      - name: Run Eslint
        run: npx eslint js --ext .js

      - name: Run Stylelint
        run: npx stylelint "**/*.css"

  infrastructure:
    needs: code-review
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository to Ubuntu
        uses: actions/checkout@v3

      - name: Install and Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Format Terraform file
        run: terraform fmt -check
        working-directory: terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

  Deploy:
    needs: infrastructure
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository to Ubuntu
        uses: actions/checkout@v3

      - name: Install and Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Upload files to S3
        run: aws s3 sync . s3://aliza-dileep-hasaan.com --delete

      - name: Invalidate Cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id E2IVDSDIA7SXP --paths /
